
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name VARCHAR(256)                        NOT NULL,
    email VARCHAR(512)                            NOT NULL,
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
    );

CREATE TABLE IF NOT EXISTS requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_description VARCHAR(256)              NOT NULL,
    requester_id BIGINT                           NOT NULL,
    created_time TIMESTAMP WITHOUT TIME ZONE      NOT NULL,
    CONSTRAINT fk_requests_to_users FOREIGN KEY (requester_id) REFERENCES users (id) ON DELETE CASCADE
    );

CREATE TABLE IF NOT EXISTS items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_name VARCHAR(256)                        NOT NULL,
    item_description VARCHAR(1024)                NOT NULL,
    item_available BOOLEAN                        NOT NULL,
    owner_id BIGINT                               NOT NULL,
    request_id BIGINT                                     ,
    CONSTRAINT fk_items_to_users FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_items_to_requests FOREIGN KEY (request_id) REFERENCES requests (id)
    );

CREATE TABLE IF NOT EXISTS bookings (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    start_time TIMESTAMP WITHOUT TIME ZONE    NOT NULL,
    end_time TIMESTAMP WITHOUT TIME ZONE      NOT NULL,
    item_id BIGINT REFERENCES items (id) ON DELETE CASCADE,
    booker_id BIGINT REFERENCES users (id) ON DELETE CASCADE,
    status VARCHAR(8) NOT NULL
    );

CREATE TABLE IF NOT EXISTS comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text VARCHAR(1024),
    author_id BIGINT REFERENCES users (id) ON DELETE CASCADE,
    item_id BIGINT REFERENCES items (id) ON DELETE CASCADE,
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL
    );